### ISSUE TITLE
'ocaml' could not be spawned

### ISSUE THREAD

**Issue by iSheeft** [T-800/REPL-Nodejs#2]
Maybe this is a stupid issue, if so I'm sorry.

Whenever I try to launch ocaml REPL, it says
```
'ocaml' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

I tried to read the code but I see `cmd = 'ocaml'`, and when I type ocaml in my bash it just works.
Did I forget something?

**Comment by etouss** [comment]
Hello sorry for the delay far too long.
Try to add ocaml to your path it may not be install in a place we look for.
Indeed use 'which ocaml' to locate the program, you can also modify the path to ocaml in the plugin source code

**Comment by iSheeft** [comment]
It's alright.

I installed ocaml with opam, so it is in my `PATH`.
I also tried to add manually what `which` returned to `PATH` but I still get the error.
But, yeah I guess the problem I have is still somehow related to it, because when I try to run my makefile from Atom, it also fails to run `ocamlbuild`.

Thanks for your help.

**Comment by lbeschastny** [comment]
@iSheeft you can fix it using [this comment][1] from rgbkrk/atom-script#98 PR.

  [1]: https://github.com/rgbkrk/atom-script/pull/98#issuecomment-40719037

**Comment by iSheeft** [comment]
Thanks a lot, sorry for the issue that didn't belong here.

**Comment by lbeschastny** [comment]
@iSheeft well, I'm not so sure that it doesn't belong here.

I mean, this problem *could* be solved on the package level.

**Comment by etouss** [comment]
You are right we will get on it as soon as possible.  Thanks for the
feedback we are glad someone was able to help you.

Le mardi 7 juillet 2015, Leonid Beschasny <notifications@github.com> a
écrit :

> @iSheeft <https://github.com/iSheeft> well, I'm not so sure that it
> doesn't belong here.
>
> I mean, this problem *could* be solved on the package level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/T-800/REPL-Nodejs/issues/2#issuecomment-119183431>.
>


-- 
Toussaint Etienne
