### ISSUE TITLE
Python2 and Python3 repl

### ISSUE THREAD

**Issue by l-d-j** [T-800/REPL-Nodejs#4]
Hi I like you REPL plugin for atom, but i'm lacking some python2 REPL. Many of mine code has to support both python 2 and 3. I would love to see a possibility to have two python REPL.

**Comment by T-800** [comment]
We just add Python2 and Python3 support in (v0.4.0) version. 
thanks for the suggest.

**Comment by l-d-j** [comment]
Thanks so much, that's awesome!
